/**
 * Client-side PDF generator for Isabella's wellness assessments.
 * Reports are generated in-session only — nothing is persisted.
 *
 * Two report types:
 *   - nutrition_assessment
 *   - recovery_resilience  (Executive Recovery & Resilience Assessment)
 *
 * Legacy alias: 'biological_age' is still accepted on inbound payloads.
 *
 * Footer disclaimer is always included.
 */

import jsPDF from 'jspdf';

const FOOTER_DISCLAIMER =
  'This assessment is educational and informational only. It is not a medical diagnosis and should not replace consultation with a qualified healthcare professional.';

export interface AssessmentReport {
  type: 'nutrition_assessment' | 'recovery_resilience';
  title?: string;
  data: any;
}

// Try to parse a fenced ```assessment-report ... ``` block.
// Returns the report and the cleaned message (block removed) so chat UI stays clean.
export function extractAssessmentReport(text: string): {
  report: AssessmentReport | null;
  cleaned: string;
} {
  if (!text) return { report: null, cleaned: text };
  const re = /```assessment-report\s*([\s\S]*?)```/i;
  const m = text.match(re);
  if (!m) return { report: null, cleaned: text };
  try {
    const parsed = JSON.parse(m[1].trim());
    if (parsed && (parsed.type === 'nutrition_assessment' || parsed.type === 'biological_age') && parsed.data) {
      return {
        report: parsed as AssessmentReport,
        cleaned: text.replace(re, '').trim(),
      };
    }
  } catch {
    // fall through
  }
  return { report: null, cleaned: text };
}

// ── PDF builder ─────────────────────────────────────────────────────────
const GOLD = '#c9a84c';
const NAVY = '#0d1b2a';
const INK = '#1a1a1a';
const MUTED = '#666666';

function header(doc: jsPDF, title: string) {
  doc.setFillColor(NAVY);
  doc.rect(0, 0, 595, 70, 'F');
  doc.setTextColor(GOLD);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('OVELA INTERACTIVE  ·  ISABELLA', 40, 28);
  doc.setTextColor('#ffffff');
  doc.setFontSize(18);
  doc.text(title, 40, 52);
}

function footer(doc: jsPDF, pageNo: number, pages: number) {
  const h = doc.internal.pageSize.getHeight();
  doc.setDrawColor(GOLD);
  doc.setLineWidth(0.5);
  doc.line(40, h - 70, 555, h - 70);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  const wrapped = doc.splitTextToSize(FOOTER_DISCLAIMER, 515);
  doc.text(wrapped, 40, h - 55);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by Isabella · ovelainteractive.com  ·  page ${pageNo} of ${pages}`, 40, h - 20);
}

function sectionTitle(doc: jsPDF, text: string, y: number) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(NAVY);
  doc.text(text, 40, y);
  doc.setDrawColor(GOLD);
  doc.setLineWidth(0.8);
  doc.line(40, y + 4, 90, y + 4);
  return y + 22;
}

function paragraph(doc: jsPDF, text: string, y: number, opts: { size?: number; color?: string } = {}) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(opts.size ?? 10);
  doc.setTextColor(opts.color ?? INK);
  const lines = doc.splitTextToSize(text, 515);
  doc.text(lines, 40, y);
  return y + lines.length * (opts.size ?? 10) * 1.4;
}

function scoreRow(doc: jsPDF, label: string, score: number, y: number) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text(label, 40, y);
  // bar
  const barX = 240, barW = 240, barH = 8;
  doc.setFillColor('#eeeeee');
  doc.rect(barX, y - 7, barW, barH, 'F');
  const pct = Math.max(0, Math.min(100, score)) / 100;
  const fillColor = score >= 75 ? '#2d8a5e' : score >= 55 ? GOLD : '#c2553a';
  doc.setFillColor(fillColor);
  doc.rect(barX, y - 7, barW * pct, barH, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text(`${score}/100`, 500, y);
  return y + 18;
}

function ensureSpace(doc: jsPDF, y: number, needed: number) {
  const h = doc.internal.pageSize.getHeight();
  if (y + needed > h - 90) {
    doc.addPage();
    return 100;
  }
  return y;
}

// ── Nutrition report (8-section enriched) ───────────────────────────────
function buildNutrition(doc: jsPDF, data: any) {
  header(doc, 'Executive Nutrition & Muscle Preservation Assessment');
  let y = 110;

  // 1. Executive summary
  if (data.executive_summary) {
    y = sectionTitle(doc, '1 · Executive summary', y);
    y = paragraph(doc, data.executive_summary, y);
    y += 8;
  }

  // Snapshot scores
  y = ensureSpace(doc, y, 180);
  y = sectionTitle(doc, 'Nutrition snapshot', y);
  const s = data.scores || {};
  y = scoreRow(doc, 'Protein', s.protein ?? 0, y);
  y = scoreRow(doc, 'Carbohydrate quality', s.carbs ?? 0, y);
  y = scoreRow(doc, 'Fat quality', s.fat ?? 0, y);
  y = scoreRow(doc, 'Hydration', s.hydration ?? 0, y);
  y = scoreRow(doc, 'Recovery support', s.recovery_support ?? 0, y);
  y += 6;
  y = scoreRow(doc, 'OVERALL NUTRITION', s.overall_nutrition ?? 0, y);
  y += 10;

  // Targets + calculation basis
  y = ensureSpace(doc, y, 160);
  y = sectionTitle(doc, 'Your daily targets', y);
  const t = data.targets || {};
  const cb = data.calculation_basis;
  if (cb?.note) {
    y = paragraph(doc, cb.note, y, { color: MUTED, size: 9 });
    y += 4;
  }
  y = paragraph(doc,
    `Calories: ~${t.daily_calories ?? '—'} kcal${t.maintenance_calories && t.maintenance_calories !== t.daily_calories ? `  (maintenance ~${t.maintenance_calories} kcal)` : ''}\n` +
    `Protein: ${t.protein_g?.low_g ?? '—'}–${t.protein_g?.high_g ?? '—'} g\n` +
    `Carbohydrates: ${t.carbs_g?.low_g ?? '—'}–${t.carbs_g?.high_g ?? '—'} g\n` +
    `Fat: ${t.fat_g?.low_g ?? '—'}–${t.fat_g?.high_g ?? '—'} g\n` +
    `Hydration: ~${t.hydration_l ?? '—'} L`, y);
  y += 6;

  // Weekly protein gap callout
  if (data.gaps?.weekly_protein_g > 0) {
    y = ensureSpace(doc, y, 50);
    doc.setFillColor('#fff8e1');
    doc.rect(40, y - 12, 515, 36, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(NAVY);
    doc.text(`Weekly protein gap: ${data.gaps.weekly_protein_g} g`, 50, y + 2);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text(`That is roughly ${data.gaps.protein_g} g/day × 7 — closing it is your fastest body-composition lever.`, 50, y + 16);
    y += 32;
  }

  // Fastest win highlight
  if (data.fastest_win) {
    y = ensureSpace(doc, y, 110);
    y = sectionTitle(doc, '⚡ Fastest win', y);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(NAVY);
    doc.text(data.fastest_win.title, 40, y); y += 16;
    y = paragraph(doc, data.fastest_win.action, y);
    if ((data.fastest_win.expected_benefits || []).length) {
      y = paragraph(doc, `Expected benefits: ${data.fastest_win.expected_benefits.join(', ')}.`, y, { color: MUTED, size: 9 });
    }
    if (data.fastest_win.closes_pct_of_weekly_gap > 0) {
      y = paragraph(doc, `This single change closes approximately ${data.fastest_win.closes_pct_of_weekly_gap}% of your weekly protein gap.`, y, { color: MUTED, size: 9 });
    }
    y += 8;
  }

  // 2. Muscle preservation
  const mp = data.muscle_preservation;
  if (mp) {
    y = ensureSpace(doc, y, 160);
    y = sectionTitle(doc, '2 · Muscle preservation', y);
    y = paragraph(doc,
      `Current protein: ${mp.current_protein_g ?? '—'} g/day\n` +
      `Recommended protein: ${mp.recommended_protein_g ?? '—'} g/day\n` +
      `Status: ${mp.status}`, y);
    y += 4;
    y = scoreRow(doc, 'Muscle preservation score', mp.score ?? 0, y);
    if ((mp.reasons || []).length) {
      y += 4;
      y = paragraph(doc, 'Why this score:', y);
      mp.reasons.forEach((r: string) => { y = ensureSpace(doc, y, 14); y = paragraph(doc, `• ${r}`, y, { color: MUTED, size: 9 }); });
    }
    if (mp.note) { y += 4; y = paragraph(doc, mp.note, y, { color: MUTED, size: 9 }); }
    y += 6;
  }

  // 3. Protein strategy + distribution + 30g swaps
  const ps = data.protein_strategy;
  if (ps) {
    y = ensureSpace(doc, y, 180);
    y = sectionTitle(doc, `3 · Protein strategy (${ps.diet_type})`, y);
    y = paragraph(doc, 'Best protein sources:', y);
    (ps.best_sources || []).forEach((src: string) => { y = ensureSpace(doc, y, 14); y = paragraph(doc, `• ${src}`, y); });
    y += 4;
    if (ps.distribution) {
      y = paragraph(doc, `Distribution status: ${ps.distribution.status}`, y, { color: MUTED, size: 9 });
      if (ps.distribution.score != null) {
        y += 2;
        y = scoreRow(doc, 'Protein distribution score', ps.distribution.score, y);
      }
      if (ps.distribution.meals) {
        ps.distribution.meals.forEach((m: any) => {
          y = ensureSpace(doc, y, 14);
          y = paragraph(doc, `   ${m.meal}: ${m.protein_g ?? '—'} g  (target 30–40 g per main meal)`, y, { color: MUTED, size: 9 });
        });
      }
      y += 4;
    }
    if ((ps.thirty_gram_options || []).length) {
      y = ensureSpace(doc, y, 80);
      y = paragraph(doc, 'To add 30 g of protein — choose ONE:', y);
      ps.thirty_gram_options.forEach((opt: string) => { y = ensureSpace(doc, y, 14); y = paragraph(doc, `✓ ${opt}`, y); });
      y += 4;
    }
    if (ps.vegetarian_alternatives) {
      y = ensureSpace(doc, y, 60);
      y = paragraph(doc, 'Vegetarian alternatives:', y, { color: MUTED, size: 9 });
      y = paragraph(doc, ps.vegetarian_alternatives.join(', '), y, { color: MUTED, size: 9 });
      y += 6;
    }
  }

  // 4. Daily meal framework
  const mf = data.daily_meal_framework;
  if (mf) {
    y = ensureSpace(doc, y, 160);
    y = sectionTitle(doc, `4 · Daily meal framework (~${mf.total_protein_g} g protein)`, y);
    (mf.meals || []).forEach((m: any) => {
      y = ensureSpace(doc, y, 36);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(NAVY);
      doc.text(`${m.meal} — ${m.protein_g} g protein`, 40, y);
      y += 14;
      y = paragraph(doc, m.example, y, { color: MUTED });
      y += 4;
    });
  }

  // 5. Metabolic support
  const ms = data.metabolic_support;
  if (ms) {
    y = ensureSpace(doc, y, 100);
    y = sectionTitle(doc, '5 · Metabolic support', y);
    y = scoreRow(doc, 'Metabolic support score', ms.score ?? 0, y);
    if ((ms.biggest_opportunities || []).length) {
      y += 4;
      y = paragraph(doc, 'Biggest opportunities:', y);
      ms.biggest_opportunities.forEach((o: string) => {
        y = ensureSpace(doc, y, 14);
        y = paragraph(doc, `• ${o}`, y);
      });
    }
    y += 6;
  }

  // 6. Resistance training
  const rt = data.resistance_training;
  if (rt) {
    y = ensureSpace(doc, y, 120);
    y = sectionTitle(doc, '6 · Resistance training recommendation', y);
    y = paragraph(doc,
      `Age: ${rt.age}    Goal: ${rt.goal}\n` +
      `• ${rt.strength_sessions_per_week} resistance sessions per week\n` +
      `• ${rt.cardio_sessions_per_week} cardio sessions per week\n` +
      `• ${rt.mobility_minutes_per_day} minutes of daily mobility work`, y);
    if (rt.reason) { y += 4; y = paragraph(doc, rt.reason, y, { color: MUTED, size: 9 }); }
    y += 6;
  }

  // 7. Biological age impact
  const bai = data.biological_age_impact;
  if (bai) {
    y = ensureSpace(doc, y, 120);
    y = sectionTitle(doc, '7 · Biological age impact factors', y);
    if ((bai.positive || []).length) {
      y = paragraph(doc, 'Positive:', y);
      bai.positive.forEach((p: string) => { y = ensureSpace(doc, y, 14); y = paragraph(doc, `✓ ${p}`, y); });
      y += 4;
    }
    if ((bai.needs_improvement || []).length) {
      y = paragraph(doc, 'Needs improvement:', y);
      bai.needs_improvement.forEach((p: string) => { y = ensureSpace(doc, y, 14); y = paragraph(doc, `⚠ ${p}`, y); });
      y += 4;
    }
    if (bai.note) { y = paragraph(doc, bai.note, y, { color: MUTED, size: 9 }); y += 6; }
  }

  // Priorities
  if ((data.improvement_priorities || []).length) {
    y = ensureSpace(doc, y, 130);
    y = sectionTitle(doc, 'Three highest-impact improvements', y);
    data.improvement_priorities.forEach((p: any, i: number) => {
      y = ensureSpace(doc, y, 50);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(NAVY);
      doc.text(`${i + 1}. ${p.title}`, 40, y);
      y += 14;
      y = paragraph(doc, p.detail, y, { color: MUTED });
      y += 4;
    });
  }

  // 8. Weekly action plan
  const wap = data.weekly_action_plan;
  if (wap) {
    y = ensureSpace(doc, y, 160);
    y = sectionTitle(doc, "8 · Isabella's weekly action plan", y);
    y = paragraph(doc, 'Your priority focus this week:', y);
    (wap.priorities || []).forEach((p: string) => {
      y = ensureSpace(doc, y, 16);
      y = paragraph(doc, `☐ ${p}`, y);
    });
    y += 6;
    y = paragraph(doc, 'Expected benefits:', y);
    (wap.expected_benefits || []).forEach((b: string) => {
      y = ensureSpace(doc, y, 14);
      y = paragraph(doc, `• ${b}`, y);
    });
    y += 4;
  }

  // 7-day plan
  if ((data.seven_day_plan || []).length) {
    y = ensureSpace(doc, y, 180);
    y = sectionTitle(doc, '7-day protein upgrade plan', y);
    data.seven_day_plan.forEach((line: string) => {
      y = ensureSpace(doc, y, 18);
      y = paragraph(doc, `• ${line}`, y);
    });
  }
}

// ── Biological age report ───────────────────────────────────────────────
function buildBioAge(doc: jsPDF, data: any) {
  header(doc, 'Biological Age Assessment');
  let y = 110;

  // Big numbers
  y = sectionTitle(doc, 'Your estimate', y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text(`Chronological age:`, 40, y);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text(`${data.chronological_age}`, 220, y);
  y += 28;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`Estimated biological age:`, 40, y);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  const delta = data.difference_years || 0;
  doc.setTextColor(delta <= 0 ? '#2d8a5e' : '#c2553a');
  doc.text(`${data.estimated_biological_age}`, 220, y);
  doc.setTextColor(INK);
  y += 28;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  const sign = delta > 0 ? `+${delta}` : `${delta}`;
  doc.text(`Difference: ${sign} years`, 40, y);
  y += 24;

  // Score breakdown
  y = ensureSpace(doc, y, 180);
  y = sectionTitle(doc, 'Score breakdown', y);
  const sc = data.scores || {};
  y = scoreRow(doc, 'Sleep', sc.sleep ?? 0, y);
  y = scoreRow(doc, 'Stress', sc.stress ?? 0, y);
  y = scoreRow(doc, 'Movement', sc.movement ?? 0, y);
  y = scoreRow(doc, 'Recovery', sc.recovery ?? 0, y);
  y = scoreRow(doc, 'Metabolic health', sc.metabolic ?? 0, y);
  y = scoreRow(doc, 'Lifestyle (alcohol/smoking)', sc.lifestyle ?? 0, y);
  y += 6;
  y = scoreRow(doc, 'LONGEVITY INDEX', sc.longevity_index ?? 0, y);
  y += 12;

  // Priorities
  y = ensureSpace(doc, y, 130);
  y = sectionTitle(doc, 'Most important improvement opportunities', y);
  (data.improvement_priorities || []).forEach((p: any, i: number) => {
    y = ensureSpace(doc, y, 50);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(NAVY);
    doc.text(`${i + 1}. ${p.title}`, 40, y);
    y += 14;
    y = paragraph(doc, p.detail, y, { color: MUTED });
    y += 4;
  });

  // Projection
  y = ensureSpace(doc, y, 100);
  y = sectionTitle(doc, 'Biological age projection', y);
  const pr = data.projection || {};
  y = paragraph(doc,
    `Estimated biological age in 6 months: ${pr.six_months_estimated_age ?? '—'}\n` +
    `Estimated biological age in 12 months: ${pr.twelve_months_estimated_age ?? '—'}\n\n` +
    (pr.note || ''), y);
}

/** Build the PDF and trigger the download. */
export function downloadAssessmentReport(report: AssessmentReport) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  if (report.type === 'nutrition_assessment') buildNutrition(doc, report.data);
  else buildBioAge(doc, report.data);

  // Apply footer to every page
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    footer(doc, i, pages);
  }

  const stamp = new Date().toISOString().slice(0, 10);
  const name = report.type === 'nutrition_assessment'
    ? `isabella-nutrition-assessment-${stamp}.pdf`
    : `isabella-biological-age-${stamp}.pdf`;
  doc.save(name);
}
