/**
 * Reader for localized SEO content generated by scripts/generate-localized-seo.ts.
 * Returns the localized payload for a given hub/category + lang, or null if
 * the lang is English or not present (caller falls back to the source English).
 */

import data from '@/data/localized-seo.json';

export interface LocalizedHubContent {
  seoTitle: string;
  seoDescription: string;
  tagline: string;
  heroIntro: string;
  /** Optional: localized long-form sections (matches source `sections[]` 1:1). */
  sections?: { heading: string; body: string }[];
  /** Optional: localized industry sub-segments (matches source `subSegments[]` 1:1). */
  subSegments?: { title: string; body: string }[];
  faqs: { question: string; answer: string }[];
}

export interface LocalizedCategoryContent {
  seoTitle: string;
  seoDescription: string;
  intro: string;
  longIntro: string;
  faqs: { question: string; answer: string }[];
}

const SUPPORTED = new Set(['es', 'fr', 'de', 'pt', 'ca']);

export function getLocalizedHub(slug: string, lang: string): LocalizedHubContent | null {
  if (!SUPPORTED.has(lang)) return null;
  const hub = (data as any).hubs?.[slug];
  return hub?.[lang] || null;
}

export function getLocalizedCategory(slug: string, lang: string): LocalizedCategoryContent | null {
  if (!SUPPORTED.has(lang)) return null;
  const cat = (data as any).categories?.[slug];
  return cat?.[lang] || null;
}
