project_id = "vrpgowcocbztclxfzssu"

[functions.ovela-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.openai-realtime-relay]
verify_jwt = false

[functions.heygen-proxy]
verify_jwt = false

[functions.transcribe]
verify_jwt = false

