project_id = "vrpgowcocbztclxfzssu"

[functions.ovela-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.openai-realtime-relay]
verify_jwt = false

[functions.heygen-proxy]
verify_jwt = false

[functions.brand-templates]
verify_jwt = false

[functions.debug-brand-context]
verify_jwt = false

[functions.load-ovela-brand]
verify_jwt = false

[functions.openai-realtime-token]
verify_jwt = false
