// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrpgowcocbztclxfzssu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycGdvd2NvY2J6dGNseGZ6c3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTU1OTcsImV4cCI6MjA2Mjc5MTU5N30.6j-g2lQ9ZPj-EQZlEuHRMhYEDx04ky_vU1Nw-4HkePA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});